
# Create services based on arguments
services:

    unite.cms_media.graphql.extender.pre_signed_url:
        parent: UniteCMS\CoreBundle\GraphQL\Schema\Extender\SchemaFileExtender
        arguments: ['%kernel.project_dir%/vendor/unite-cms/media-bundle/Resources/GraphQL/Schema/pre-signed-url.graphql']
        tags:
            - { name: 'unite.graphql.schema_extender', position: !php/const UniteCMS\CoreBundle\GraphQL\Schema\Extender\SchemaExtenderInterface::EXTENDER_AFTER }

