# Contains all security related services.
services:

  UniteCMS\RegistrationBundle\Security\Voter\CreateOrganizationVoter:
    public: false
    tags: [security.voter]


  UniteCMS\RegistrationBundle\Subscriber\CreateOrganizationSubscriber:
    public: false
    arguments: ['@security.token_storage']
    tags:
      - { name: doctrine.event_listener, event: prePersist }


  # This allows controller actions to inject services in the method call instead of calling $this->get('').
  UniteCMS\RegistrationBundle\Controller\:
    resource: '../../Controller'
    autowire: true
    tags: ['controller.service_arguments']
