services:

  # A collection input field that allows to add multiple, repeatable sub fields
  UniteCMS\CollectionFieldBundle\Field\Types\CollectionFieldType:
    tags: [unite_cms.field_type]
    arguments: ['@unite.cms.collection_field.collection_field_type_factory', '@unite.cms.field_type_manager', '@unite.cms.field_type.config_factory.table_view', '@security.authorization_checker']


  unite.cms.collection_field.collection_field_type_factory:
    class: UniteCMS\CollectionFieldBundle\SchemaType\Factories\CollectionFieldTypeFactory
    tags: [unite_cms.graphql.schema_type_factory]
    arguments: ['@unite.cms.field_type_manager', '@security.authorization_checker']
