<?php
/**
 * Created by PhpStorm.
 * User: franzwilding
 * Date: 31.08.18
 * Time: 10:05
 */

namespace UniteCMS\CoreBundle\Tests\Service;

use UniteCMS\CoreBundle\Entity\Domain;
use UniteCMS\CoreBundle\Entity\Organization;
use UniteCMS\CoreBundle\Tests\DatabaseAwareTestCase;

class DomainDefinitionParserTest extends DatabaseAwareTestCase
{
    // NOTE: parsing the domain is tested in CreateDomainCommandTest.
    private $domainConfig = '';
    private $validDomainConfig = '';

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->domainConfig = '{
            "title": "My test Domain",
            "identifier": "my_test_domain",
            "variables": {
                "@query": "query { type }",
                "@v0": "Title",
                "@v1": "@v0",
                "@text_field": {
                    "title": "@v1",
                    "identifier": "@v2",
                    "type": "text"
                },
                "@v2": "title"
            },
            "permissions": {
                "view domain": "true",
                "update domain": "true"
            },
            "content_types": [
                {
                    "title": "First Content Type",
                    "identifier": "first_ct",
                    "preview": {
                        "url": "https://example.com",
                        "query": "@query"
                    },
                    "content_label": "{title}",
                    "fields": [
                        "@text_field",
                        {
                          "title": "Slug",
                          "identifier": "slug",
                          "type": "text"
                        },
                        {
                          "title": "Position",
                          "identifier": "position",
                          "type": "sortindex"
                        }
                    ],
                    "views": [
                        {
                          "title": "All",
                          "identifier": "all",
                          "type": "sortable",
                          "settings": {
                            "sort_field": "position"
                          }
                        }
                    ],
                    "permissions": {
                        "delete content": "false"
                    },
                    "webhooks": [
                        {
                          "query": "@query",
                          "url": "https://example.com",
                          "check_ssl": true,
                          "condition": "true"
                        }
                    ]
                },
                {
                    "title": "Other Content Type",
                    "identifier": "other_ct",
                    "icon": "file"
                }
            ],
            "setting_types": [
                {
                    "title": "First Setting Type",
                    "identifier": "first_st",
                    "icon": "file",
                    "fields": [
                        "@text_field"
                    ],
                    "permissions": {
                        "update setting": "false"
                    },
                    "webhooks": [
                        {
                          "query": "@query",
                          "url": "https://example.com",
                          "check_ssl": true,
                          "condition": "true"
                        }
                    ]
                },
                {
                    "title": "Other Setting Type",
                    "identifier": "other_st"
                }
            ],
            "domain_member_types": [
                {
                    "title": "Any",
                    "identifier": "any",
                    "domain_member_label": "Any",
                    "fields": ["@text_field"],
                    "permissions": {
                        "view member": "false",
                        "list member": "false",
                        "create member": "false",
                        "update member": "false",
                        "delete member": "false"
                    }
                }
            ]
        }';

        $this->validDomainConfig = '{
            "title": "My test Domain",
            "identifier": "my_test_domain",
            "content_types": [
                {
                    "title": "First Content Type",
                    "identifier": "first_ct",
                    "preview": {
                        "url": "https://example.com",
                        "query": "query { type }"
                    },
                    "content_label": "{title}",
                    "fields": [
                        {
                            "title": "Title",
                            "identifier": "title",
                            "type": "text",
                            "permissions": {
                                "list field": "true",
                                "view field": "true",
                                "update field": "true"
                            }
                        },
                        {
                          "title": "Slug",
                          "identifier": "slug",
                          "type": "text",
                          "permissions": {
                            "list field": "true",
                            "view field": "true",
                            "update field": "true"
                          }
                        },
                        {
                          "title": "Position",
                          "identifier": "position",
                          "type": "sortindex",
                            "permissions": {
                                "list field": "true",
                                "view field": "true",
                                "update field": "true"
                            }
                        }
                    ],
                    "views": [
                        {
                          "title": "All",
                          "identifier": "all",
                          "type": "sortable",
                          "settings": {
                            "sort_field": "position"
                          }
                        }
                    ],
                    "permissions": {
                        "view content": "true",
                        "list content": "true",
                        "create content": "member.type == \"editor\"",
                        "update content": "member.type == \"editor\"",
                        "delete content": "false",
                        "translate content": "member.type == \"editor\""
                    },
                    "webhooks": [
                        {
                            "query": "query { type }",
                            "url": "https://example.com",
                            "check_ssl": true,
                            "content_type": "json",
                            "condition": "true"
                        }
                    ]
                },
                {
                    "title": "Other Content Type",
                    "identifier": "other_ct",
                    "icon": "file",
                    "content_label": "{type} #{id}",
                    "fields": [],
                    "views": [
                        {
                            "title": "All",
                            "identifier": "all",
                            "type": "table"
                        }
                    ],
                    "permissions": {
                        "view content": "true",
                        "list content": "true",
                        "create content": "member.type == \"editor\"",
                        "update content": "member.type == \"editor\"",
                        "delete content": "member.type == \"editor\"",
                        "translate content": "member.type == \"editor\""
                    }
                }
            ],
            "setting_types": [
                {
                    "title": "First Setting Type",
                    "identifier": "first_st",
                    "icon": "file",
                    "fields": [
                        {
                            "title": "Title",
                            "identifier": "title",
                            "type": "text",
                            "permissions": {
                                "list field": "true",
                                "view field": "true",
                                "update field": "true"
                            }
                        }
                    ],
                    "permissions": {
                        "view setting": "true",
                        "update setting": "false"
                    },
                    "webhooks": [
                        {
                          "query": "query { type }",
                          "url": "https://example.com",
                          "check_ssl": true,
                          "content_type": "json",
                          "condition": "true"
                        }
                    ]
                },
                {
                    "title": "Other Setting Type",
                    "identifier": "other_st",
                    "fields": [],
                    "permissions": {
                        "view setting": "true",
                        "update setting": "member.type == \"editor\""
                    }
                }
            ],
            "domain_member_types": [
                {
                    "title": "Any",
                    "identifier": "any",
                    "domain_member_label": "Any",
                    "fields": [
                        {
                            "title": "Title",
                            "identifier": "title",
                            "type": "text",
                            "permissions": {
                                "list field": "true",
                                "view field": "true",
                                "update field": "true"
                            }
                        }
                    ],
                    "permissions": {
                        "view member": "false",
                        "list member": "false",
                        "create member": "false",
                        "update member": "false",
                        "delete member": "false"
                    }
                }
            ],
            "permissions": {
                "view domain": "true",
                "update domain": "true"
            }
        }';
    }

    public function testDomainSerialization() {

        $org = new Organization();
        $org->setTitle('Org')->setIdentifier('org');
        $domain = static::$container->get('unite.cms.domain_definition_parser')->parse($this->domainConfig);
        $domain->setOrganization($org);

        $this->em->persist($org);
        $this->em->persist($domain);
        $this->em->flush();

        /**
         * @var Domain[]
         */
        $domains = $this->em->getRepository('UniteCMSCoreBundle:Domain')->findAll();
        $this->assertCount(1, $domains);

        $parsedDomain = static::$container->get('unite.cms.domain_definition_parser')->serialize($domain);
        $this->assertJsonStringEqualsJsonString($this->validDomainConfig, $parsedDomain);
    }
}