unite_cms_core_api:
    path: /{!unite_domain}
    methods: [POST, OPTIONS]
    controller: UniteCMS\CoreBundle\Controller\ApiController::api
    requirements:
        unite_domain: '[a-z0-9_]+'

unite_cms_admin:
    path: /{!unite_domain}/{path}
    methods: [GET]
    controller: UniteCMS\AdminBundle\Controller\AdminController::app
    defaults:
        path: ''
    requirements:
        path: '.*'
        unite_domain: '[a-z0-9_]+'


# Routes for the default domain (api + admin)
unite_cms_core_api_default:
    path: /{unite_domain}
    methods: [POST, OPTIONS]
    controller: UniteCMS\CoreBundle\Controller\ApiController::api
    requirements:
        unite_domain: '[a-z0-9_]+'
    defaults:
        unite_domain: 'default'

unite_cms_core_admin_default:
    path: /{unite_domain}/{path}
    methods: [GET]
    controller: UniteCMS\AdminBundle\Controller\AdminController::app
    defaults:
        unite_domain: 'default'
        path: ''
    requirements:
        path: '.*'
        unite_domain: '[a-z0-9_]+'
