imports:
  - { resource: services.core.yml }
  - { resource: services.commands.yml }
  - { resource: services.graphql.yml }
  - { resource: services.security.yml }
  - { resource: services.fieldTypes.yml }
  - { resource: services.viewTypes.yml }
  - { resource: services.validators.yml }
  - { resource: services.doctrineListener.yml }
  - { resource: services.kernelListener.yml }
  - { resource: services.serialization.yml }
  - { resource: services.twig.yml }

services:

  _defaults:
    bind:
      $mailerSender: '%mailer_sender%'
      $kernelDebug: '%kernel.debug%'

  # This allows controller actions to inject services in the method call instead of calling $this->get('').
  UniteCMS\CoreBundle\Controller\:
    resource: '../../Controller'
    autowire: true
    tags: ['controller.service_arguments']
