
# Create services based on arguments
services:

    unite.cms_core.graphql.schema_cache.adapter:
        class: Symfony\Component\Cache\Adapter\PhpFilesAdapter
        factory: ['Symfony\Component\Cache\Adapter\PhpFilesAdapter', 'createSystemCache']
        arguments:
            - 'unite'
            - 0
            - 0
            - '%kernel.cache_dir%'

    unite.cms_core.graphql.provider.unite_cms:
        parent: UniteCMS\CoreBundle\GraphQL\Schema\Provider\SchemaFileProvider
        arguments: ['%kernel.project_dir%/vendor/unite-cms/core-bundle/Resources/GraphQL/Schema/unite-cms.graphql']
        tags: ['unite.graphql.schema_provider']

    unite.cms_core.graphql.extender.email_password_reset:
        parent: UniteCMS\CoreBundle\GraphQL\Schema\Extender\SchemaFileExtender
        arguments: ['%kernel.project_dir%/vendor/unite-cms/core-bundle/Resources/GraphQL/Schema/email-password-reset.graphql']
        tags:
            - { name: 'unite.graphql.schema_extender', position: !php/const UniteCMS\CoreBundle\GraphQL\Schema\Extender\SchemaExtenderInterface::EXTENDER_AFTER }

    unite.cms_core.graphql.extender.email_account_activate:
        parent: UniteCMS\CoreBundle\GraphQL\Schema\Extender\SchemaFileExtender
        arguments: ['%kernel.project_dir%/vendor/unite-cms/core-bundle/Resources/GraphQL/Schema/email-account-activate.graphql']
        tags:
            - { name: 'unite.graphql.schema_extender', position: !php/const UniteCMS\CoreBundle\GraphQL\Schema\Extender\SchemaExtenderInterface::EXTENDER_AFTER }

    unite.cms_core.graphql.extender.email_change:
        parent: UniteCMS\CoreBundle\GraphQL\Schema\Extender\SchemaFileExtender
        arguments: ['%kernel.project_dir%/vendor/unite-cms/core-bundle/Resources/GraphQL/Schema/email-change.graphql']
        tags:
            - { name: 'unite.graphql.schema_extender', position: !php/const UniteCMS\CoreBundle\GraphQL\Schema\Extender\SchemaExtenderInterface::EXTENDER_AFTER }

    unite.cms_core.graphql.extender.email_invite:
        parent: UniteCMS\CoreBundle\GraphQL\Schema\Extender\SchemaFileExtender
        arguments: ['%kernel.project_dir%/vendor/unite-cms/core-bundle/Resources/GraphQL/Schema/email-invite.graphql']
        tags:
            - { name: 'unite.graphql.schema_extender', position: !php/const UniteCMS\CoreBundle\GraphQL\Schema\Extender\SchemaExtenderInterface::EXTENDER_AFTER }
