# Contains all symfony kernel event listeners.
services:

  # Handling HTTP CORS requests
  UniteCMS\CoreBundle\Subscriber\CorsListener:
    public: false
    arguments: ['@security.firewall.map', '@security.token_storage']
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 10 }
      - { name: kernel.event_listener, event: kernel.response }

  # When accepting or rejecting an invitation, org admins should be notified.
  UniteCMS\CoreBundle\EventSubscriber\InvitationAdminNotifier:
    arguments: ['@mailer', '@templating.engine.twig', '@translator', '@logger', '%mailer_sender%']
    public: false
    tags:
      - { name: kernel.event_subscriber }