# Register all commands as services
services:

    UniteCMS\CoreBundle\Command\CreateDomainCommand:
        arguments: ['@doctrine.orm.default_entity_manager', '@validator', '@unite.cms.domain_config_manager']
        tags:
            - { name: 'console.command', command: 'unite:domain:create' }

    UniteCMS\CoreBundle\Command\ImportDomainCommand:
        arguments: ['@doctrine.orm.default_entity_manager', '@validator', '@unite.cms.domain_config_manager', '@request_stack', '@security.token_storage']
        tags:
            - { name: 'console.command', command: 'unite:domain:import' }

    UniteCMS\CoreBundle\Command\ListDomainCommand:
        arguments: ['@doctrine.orm.default_entity_manager', '@unite.cms.domain_config_manager']
        tags:
            - { name: 'console.command', command: 'unite:domain:list' }

    UniteCMS\CoreBundle\Command\CreateOrganizationCommand:
        arguments: ['@doctrine.orm.default_entity_manager', '@validator']
        tags:
            - { name: 'console.command', command: 'unite:organization:create' }

    UniteCMS\CoreBundle\Command\CreatePlatformAdminCommand:
        arguments: ['@doctrine.orm.default_entity_manager', '@validator', '@security.password_encoder']
        tags:
            - { name: 'console.command', command: 'unite:user:create' }

    UniteCMS\CoreBundle\Command\VersionFileDumper:
        arguments: ['@kernel', '%kernel.project_dir%']
        tags:
            - { name: 'console.command', command: 'unite:versionfile:dump' }