
# Create services based on arguments
services:

    unite.cms_admin.graphql.provider:
        parent: UniteCMS\CoreBundle\GraphQL\Schema\Provider\SchemaFileProvider
        arguments: ['%kernel.project_dir%/vendor/unite-cms/admin-bundle/Resources/GraphQL/Schema/unite-admin.graphql']
        tags: ['unite.graphql.schema_provider']
